// get all user
GET http://localhost:5000/users


// Create User
###
POST http://localhost:5000/users
Content-Type: application/json

{
  "name": "Ian",
  "email": "ian@gmail.com",
  "password": "password",
  "confPassword": "password",
  "role": "user"
}

// Update User
###
PATCH http://localhost:5000/users/37cabcd2-11fb-45f7-b7bd-d4858017638f
Content-Type: application/json

{
  "name": "Virgi",
  "email": "admin@gmail.com",
  "password": "password",
  "confPassword": "password",
  "role": "admin"
}

// Delete user
###
DELETE http://localhost:5000/users/37cabcd2-11fb-45f7-b7bd-d4858017638f

// Get single data
###
GET http://localhost:5000/users/37cabcd2-11fb-45f7-b7bd-d4858017638f

// Login
###
POST http://localhost:5000/login
Content-Type: application/json

{   
  "email" : "ian@gmail.com",
  "password": "password" 
}

###
GET http://localhost:5000/me