// Create a user
POST http://localhost:5000/users

content-type: application/json

{
    "name": "Virgi",
    "email": "admin@gmail.com",
    "password": "password",
    "role": "admin"
}
###
// get all user
GET http://localhost:5000/users
